import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import UseStateHook from './Components/UseStateHook' 
import UseEffectHook from './Components/UseEffectHook' 
import UseContextHook from './Components/UseContextHook' 
import UseMemoHook from './Components/UseMemoHook' 
import UseReducerHook from './Components/UseReducerHook' 
import UseCallbackHook from './Components/UseCallbackHook' 
import UseRefHook from './Components/UseRefHook' 



const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hook Demos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.ico?v=1.1" />
      </Head>

      
      {/* <UseStateHook />
      <UseEffectHook />
      <UseContextHook />
      <UseMemoHook />
      <UseReducerHook />
      <UseCallbackHook /> */}
      <UseRefHook />

    </div>
  )
}

export default Home
